package initx

import (
	"strings"
	"testing"
)

// tail is the fixed part of every generated Dockerfile after the
// inventory-driven lines.
const tail = `RUN curl -fsSL https://claude.ai/install.sh | bash
ENV PATH="/root/.local/bin:${PATH}"

RUN claude plugin marketplace add anthropics/claude-plugins-official \
 && claude plugin install superpowers@claude-plugins-official

ENV IS_SANDBOX=1
RUN mkdir -p /workspace
WORKDIR /workspace
`

func TestRenderDockerfile(t *testing.T) {
	cases := []struct {
		name string
		inv  Inventory
		want string
	}{
		{
			name: "minimal",
			inv:  Inventory{BaseImage: "debian:bookworm-slim"},
			want: "# Generated by ai-fleet init.\nFROM debian:bookworm-slim\n\n" + tail,
		},
		{
			name: "packages and env",
			inv: Inventory{
				BaseImage: "golang:1.26-bookworm",
				Packages:  []string{"make", "protobuf-compiler"},
				Env:       map[string]string{"GOTOOLCHAIN": "local"},
			},
			want: "# Generated by ai-fleet init.\nFROM golang:1.26-bookworm\n\n" +
				"RUN apt-get update && apt-get install -y --no-install-recommends make protobuf-compiler \\\n" +
				" && rm -rf /var/lib/apt/lists/*\n\n" +
				"ENV GOTOOLCHAIN=\"local\"\n\n" + tail,
		},
		{
			name: "env only",
			inv:  Inventory{BaseImage: "debian:bookworm-slim", Env: map[string]string{"A": "1", "B": "2"}},
			want: "# Generated by ai-fleet init.\nFROM debian:bookworm-slim\n\n" +
				"ENV A=\"1\"\nENV B=\"2\"\n\n" + tail,
		},
		{
			name: "env value with spaces stays one instruction",
			inv:  Inventory{BaseImage: "debian:bookworm-slim", Env: map[string]string{"CFLAGS": "-O2 -g"}},
			want: "# Generated by ai-fleet init.\nFROM debian:bookworm-slim\n\n" +
				"ENV CFLAGS=\"-O2 -g\"\n\n" + tail,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := RenderDockerfile(c.inv)
			if err != nil {
				t.Fatal(err)
			}
			if string(got) != c.want {
				t.Errorf("rendered:\n%s\nwant:\n%s", got, c.want)
			}
		})
	}
}

func TestInventoryPromptEmbedded(t *testing.T) {
	for _, needle := range []string{"base_image", "packages", "env", "Debian"} {
		if !strings.Contains(inventoryPrompt, needle) {
			t.Errorf("inventory prompt is missing %q", needle)
		}
	}
}
