package initx

import (
	"bytes"
	_ "embed"
	"strings"
	"text/template"
)

//go:embed inventory-prompt.md
var inventoryPrompt string

//go:embed dockerfile.tmpl
var dockerfileTmpl string

var dockerfileTemplate = template.Must(template.New("dockerfile").
	Funcs(template.FuncMap{"join": strings.Join}).
	Parse(dockerfileTmpl))

// RenderDockerfile fills the embedded template with the inventory. The
// template header is exactly "# Generated by ai-fleet init." — the file is
// committed and meant to be hand-edited afterwards.
func RenderDockerfile(inv Inventory) ([]byte, error) {
	var b bytes.Buffer
	if err := dockerfileTemplate.Execute(&b, inv); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
