package initx

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGitignoreContent(t *testing.T) {
	got := GitignoreContent("proj")
	want := "*\n!.gitignore\n!proj.ai-fleet.dockerfile\n"
	if got != want {
		t.Errorf("GitignoreContent = %q, want %q", got, want)
	}
}

func TestWriteFilesAndResolveProject(t *testing.T) {
	root := t.TempDir()
	c := Config{Name: "proj", Hash: "a1b2c3d4"}
	df := []byte("# Generated by ai-fleet init.\nFROM debian:bookworm-slim\n")

	dfPath, err := WriteFiles(root, c, df)
	if err != nil {
		t.Fatal(err)
	}
	if dfPath != filepath.Join(root, ".ai-fleet", "proj.ai-fleet.dockerfile") {
		t.Errorf("dockerfile path = %q", dfPath)
	}
	for _, f := range []string{".gitignore", "ai-fleet.ini", "proj.ai-fleet.dockerfile"} {
		if _, err := os.Stat(filepath.Join(root, ".ai-fleet", f)); err != nil {
			t.Errorf("missing %s: %v", f, err)
		}
	}
	got, _ := os.ReadFile(dfPath)
	if string(got) != string(df) {
		t.Errorf("dockerfile content = %q", got)
	}

	path, repo, err := ResolveProject(root)
	if err != nil {
		t.Fatal(err)
	}
	if path != dfPath || repo != "ai-fleet/proj-a1b2c3d4" {
		t.Errorf("ResolveProject = %q, %q", path, repo)
	}
}

func TestWriteFilesKeepsExistingRunsDir(t *testing.T) {
	// deploy unit creates .ai-fleet/runs/ on its own; init must coexist.
	root := t.TempDir()
	runs := filepath.Join(root, ".ai-fleet", "runs", "x")
	if err := os.MkdirAll(runs, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := WriteFiles(root, Config{Name: "p", Hash: "h1h2h3h4"}, []byte("FROM x\n")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(runs); err != nil {
		t.Errorf("runs dir was disturbed: %v", err)
	}
}

func TestResolveProjectNotInitialized(t *testing.T) {
	_, _, err := ResolveProject(t.TempDir())
	if err == nil || !strings.Contains(err.Error(), "ai-fleet init") {
		t.Errorf("error = %v, want mention of `ai-fleet init`", err)
	}
}
