# Generated by ai-fleet init.
FROM golang:1.26-bookworm

RUN curl -fsSL https://claude.ai/install.sh | bash
ENV PATH="/root/.local/bin:${PATH}"

RUN claude plugin marketplace add anthropics/claude-plugins-official \
 && claude plugin install superpowers@claude-plugins-official

ENV IS_SANDBOX=1
RUN mkdir -p /workspace
WORKDIR /workspace
