package run

import (
	"os"
	"testing"

	"github.com/altafard/ai-fleet/internal/dockerx"
	"github.com/altafard/ai-fleet/internal/initx"
)

// The tag `ai-fleet init` builds and the tag `deploy unit` resolves for the
// same project state are derived independently, in two packages. They must
// stay identical or every deploy rebuilds an image init already built.
func TestGeneratedImageTagMatchesInit(t *testing.T) {
	root := t.TempDir()
	c := initx.Config{Name: "proj", Hash: "a1b2c3d4"}
	df := []byte("# Generated by ai-fleet init.\nFROM debian:bookworm-slim\n")
	if _, err := initx.WriteFiles(root, c, df); err != nil {
		t.Fatal(err)
	}
	initTag := initx.ImageRepo(c.Name, c.Hash) + ":" + dockerx.ContentTag(df)

	dfPath, repo, err := initx.ResolveProject(root)
	if err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(dfPath)
	if err != nil {
		t.Fatal(err)
	}
	// Mirrors the tag selection in runPhases for the generated-Dockerfile path.
	deployTag := repo + ":" + dockerx.ContentTag(content)

	if deployTag != initTag {
		t.Errorf("deploy tag = %q, init tag = %q", deployTag, initTag)
	}
}
